# This file was generated by GoReleaser. DO NOT EDIT.
cask "uaa-cli" do
  version "0.21.0"

  on_macos do
    on_intel do
      sha256 "7419ff82a375d5a0ef944220b6d86fed1314efe5e730f87053a92c80b48386b7"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-darwin-amd64-#{version}"
      binary "uaa-darwin-amd64-0.21.0", target: "uaa"
    end
    on_arm do
      sha256 "36146ecf705d41ac91344df3bb9f2b1a26c65d77001addd2aa057bf024e4ac5c"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-darwin-arm64-#{version}"
      binary "uaa-darwin-arm64-0.21.0", target: "uaa"
    end
  end

  on_linux do
    on_intel do
      sha256 "1df299f330194ff75c271b445251be63fba1a1ed87b3542861675b1c20fd2f24"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-linux-amd64-#{version}"
      binary "uaa-linux-amd64-0.21.0", target: "uaa"
    end
    on_arm do
      sha256 "a8baff9ced85dc7e3b2a750135424235b18e9287022b8fc7e79fea292ec7717c"
      url "https://github.com/cloudfoundry/uaa-cli/releases/download/v#{version}/uaa-linux-arm64-#{version}"
      binary "uaa-linux-arm64-0.21.0", target: "uaa"
    end
  end

  name "uaa-cli"
  desc "CLI for UAA written in Go"
  homepage "https://github.com/cloudfoundry/uaa-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "uaa-cli",
    ]

  postflight do
    if OS.mac?
      Dir.glob("#{staged_path}/uaa*").each do |file|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", file]
      end
    end
  end

  # No zap stanza required

end
